# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 453)
        self.txtInfor = QtWidgets.QTextEdit(Form)
        self.txtInfor.setGeometry(QtCore.QRect(130, 110, 371, 71))
        self.txtInfor.setObjectName("txtInfor")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(290, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtSign = QtWidgets.QTextEdit(Form)
        self.txtSign.setGeometry(QtCore.QRect(130, 230, 371, 71))
        self.txtSign.setObjectName("txtSign")
        self.btnSign = QtWidgets.QPushButton(Form)
        self.btnSign.setGeometry(QtCore.QRect(160, 350, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSign.setFont(font)
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(Form)
        self.btnVerify.setGeometry(QtCore.QRect(390, 350, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnVerify.setFont(font)
        self.btnVerify.setObjectName("btnVerify")
        self.btnKeys = QtWidgets.QPushButton(Form)
        self.btnKeys.setGeometry(QtCore.QRect(480, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnKeys.setFont(font)
        self.btnKeys.setObjectName("btnKeys")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ECC CIPHER"))
        self.label_2.setText(_translate("Form", "Information:"))
        self.label_3.setText(_translate("Form", "Signature:"))
        self.btnSign.setText(_translate("Form", "Sign"))
        self.btnVerify.setText(_translate("Form", "Verify"))
        self.btnKeys.setText(_translate("Form", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
