# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 20, 131, 16))
        self.label.setObjectName("label")
        self.txtPlainText = QtWidgets.QLabel(self.centralwidget)
        self.txtPlainText.setGeometry(QtCore.QRect(80, 100, 47, 13))
        self.txtPlainText.setObjectName("txtPlainText")
        self.txtCipherText = QtWidgets.QLabel(self.centralwidget)
        self.txtCipherText.setGeometry(QtCore.QRect(90, 240, 47, 13))
        self.txtCipherText.setObjectName("txtCipherText")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 90, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 240, 47, 13))
        self.label_5.setObjectName("label_5")
        self.textPlantext = QtWidgets.QTextEdit(self.centralwidget)
        self.textPlantext.setGeometry(QtCore.QRect(90, 130, 281, 71))
        self.textPlantext.setObjectName("textPlantext")
        self.txtCipherText_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCipherText_2.setGeometry(QtCore.QRect(80, 280, 281, 71))
        self.txtCipherText_2.setObjectName("txtCipherText_2")
        self.txtInfor = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInfor.setGeometry(QtCore.QRect(470, 120, 271, 71))
        self.txtInfor.setObjectName("txtInfor")
        self.txtSign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSign.setGeometry(QtCore.QRect(480, 290, 281, 71))
        self.txtSign.setObjectName("txtSign")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(40, 380, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(220, 380, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(400, 380, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(630, 390, 75, 23))
        self.btnVerify.setObjectName("btnVerify")
        self.btnGenKeys = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenKeys.setGeometry(QtCore.QRect(490, 40, 91, 23))
        self.btnGenKeys.setObjectName("btnGenKeys")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "RSA Cipher"))
        self.txtPlainText.setText(_translate("mainWindow", "Plain Text:"))
        self.txtCipherText.setText(_translate("mainWindow", "Cipher Text:"))
        self.label_4.setText(_translate("mainWindow", "Information:"))
        self.label_5.setText(_translate("mainWindow", "Signature:"))
        self.btnEncrypt.setText(_translate("mainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("mainWindow", "Decrypt"))
        self.btnSign.setText(_translate("mainWindow", "Sign"))
        self.btnVerify.setText(_translate("mainWindow", "Verify"))
        self.btnGenKeys.setText(_translate("mainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
